<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>use.perl.org journal of jk2addict: Error.pms try/catch gotcha in unit tests</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the
bottom of the topbar */
      }
    </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script
src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/static/ico/favicon.ico">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse"
data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><img src="/static/img/slashhead.png"/></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Home</a></li>
              <li><a href="/about/">About</a></li>
              <li><a href="/authors/">Authors</a></li>
              <li><a href="/journals/">Journals</a></li>
              <li><a href="/stories/">Stories</a></li>
            </ul>
            <p class="navbar-text">All the Perl that's Practical to Extract and Report</p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>



<div class="container">

<div class="row">

<div class="span4">
<h1>Error.pms try/catch gotcha in unit tests</h1>
<h2><a href="/user/jk2addict/">jk2addict</a> on 2005-07-21T23:58:48</h2>
</div> <!-- /span4 -->


<div class="span8">
<p><p>
I'm such and idiot. I can't believe I never noticed this before. It's quite a dangerous oversight too since it meant tests didn't register a pass or a fail; no output at all which threw off the test counts. Don't let this happen to you.
</p>
<pre>
---some.t---
use Test::More tests => 2;
use Error ':try';

use_ok('MyModule');

try {
   MyModule->foo('badparam');
} catch with MyModule::Exception {
    pass;
} otherwise {
    fail;
};
</pre>

<p>
Of course, if the module throws the exception, we pass. If it throws another exception (or die), we fail. But, if the module unexpectedly succeeds, we neither fail nor pass. That's not so bad right? THe count mismatch would cause the test to fail right? Sure, but picture this:
</p>
<pre>
---some.t---
use Test::More tests => 2;
use Error ':try';

use_ok('MyModule');

try {
   MyModule->foo('badparam');
} catch with MyModule::Exception {
    pass;
} otherwise {
    fail;
};

ok('added this test later in this huge test file');
</pre>

<p>
In this scenerio, you've added a test but forgot to update the test plan count. Now you've declared 2 tests and passed 2 tests. No failures and you never know a completely failing test...didn't. This is ever more true if you're using no_plan. Probably another reason not to ever do that. :-)
</p>

<p>
Ths answer of course is to put a fail in the try block. Not something that seams obvious upon first thought. 
</p>
<pre>
---some.t---
use Test::More tests => 2;
use Error ':try';

use_ok('MyModule');

try {
   MyModule->foo('badparam');

    fail;
} catch with MyModule::Exception {
    pass;
} otherwise {
    fail;
};
</pre>

<p>
Boy do I have a lot of test files to double check. That was a painful lesson. For some reason, part of me expected otherwise to get called when no exception was thrown, but that's silly in retrospect.
</p></p>


<hr/>



<h2>another gotcha</h2>
<h3><a href="/user/perrin/">perrin</a> on 2005-07-22T04:36:51</h3>
Your sample code is missing closing semi-colons on the try() calls.  I'm guessing your real code doesn't have this problem.



<blockquote>

<h2>Re:another gotcha</h2>
<h3><a href="/user/jk2addict/">jk2addict</a> on 2005-07-22T12:42:37</h3>
Correct. That's a typo for this post. I'm a ; over-user at heart, so they all had the sem-colons in the real code.<br><br>Just out of curiousity, why is that a problem with try in Error?



<blockquote>

<h2>Re:another gotcha</h2>
<h3><a href="/user/perrin/">perrin</a> on 2005-07-22T17:01:56</h3>
The try() is just a subroutine call, so it needs a ; at the end of the line like anything else.  This is yet another problem with the try/catch syntax in Error.pm.





</blockquote>

</blockquote>


<h2>Re:</h2>
<h3><a href="/user/Aristotle/">Aristotle</a> on 2005-07-22T09:19:44</h3>
I believe you want to take a look at <a href="http://search.cpan.org/dist/Test-Exception/" title="cpan.org">Test::Exception</a cpan.org>.



<blockquote>

<h2>Re:</h2>
<h3><a href="/user/jk2addict/">jk2addict</a> on 2005-07-22T12:48:11</h3>
I was thinking about using Test::Exception way back when, but I decided against it. I didn't want to skip all of those tests everywhere just because it wasn't installed; especially when I could do mostly the same ting in a simple try statement.



<blockquote>

<h2>Re:</h2>
<h3><a href="/user/jk2addict/">jk2addict</a> on 2005-07-22T12:52:34</h3>
To add to that, Err is already a PREREQ for the dist.





</div> <!-- /span8 -->

</div> <!-- row -->
</div> <!-- /container -->



    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>

